# Generated by Django 3.1.6 on 2021-02-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_img_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
