# Generated by Django 3.1.6 on 2021-02-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_img_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_1',
            fields=[
                ('userid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('is_voted', models.BooleanField(default=False)),
            ],
        ),
    ]
