# Generated by Django 3.1.6 on 2021-02-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_user_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='update_person',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_1',
            name='mvp_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_1',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
