# Generated by Django 3.1.6 on 2021-02-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210222_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_1',
            name='wx_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='img',
            name='update_person',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_1',
            name='userid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
