# Generated by Django 3.1.6 on 2021-02-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20210225_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='delete_vote',
            field=models.IntegerField(default=0),
        ),
    ]
