# Generated by Django 3.1.6 on 2021-02-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_img_delete_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_1',
            name='is_delete_voted',
            field=models.BooleanField(default=False),
        ),
    ]
