# Generated by Django 3.1.6 on 2021-02-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_user_1_is_delete_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_1',
            name='is_delete_voted',
        ),
        migrations.RemoveField(
            model_name='user_1',
            name='is_voted',
        ),
        migrations.AddField(
            model_name='user_1',
            name='last_delete_vote_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user_1',
            name='last_vote_date',
            field=models.DateField(null=True),
        ),
    ]
