# Generated by Django 3.1.6 on 2021-02-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20210226_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='wx_ids',
            fields=[
                ('wx_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
