# Generated by Django 3.1.6 on 2021-03-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_wx_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_1',
            name='last_vote_date',
            field=models.DateTimeField(null=True),
        ),
    ]
