# Generated by Django 3.1.6 on 2021-03-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20210308_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
